# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-29 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_ip', models.CharField(max_length=20, verbose_name='应用机器ip')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('account', models.CharField(max_length=100, verbose_name='机器账号')),
                ('password', models.CharField(max_length=100, verbose_name='机器密码')),
                ('app_directory', models.CharField(max_length=500, verbose_name='应用目录')),
                ('middleware_name', models.CharField(max_length=100, verbose_name='中间件账号')),
                ('middleware_pass', models.CharField(max_length=100, verbose_name='中间件密码')),
                ('url', models.CharField(max_length=500, verbose_name='url路径')),
                ('upload_path', models.CharField(max_length=500, verbose_name='jar包上传路径')),
                ('port', models.CharField(max_length=10, verbose_name='进程端口号')),
                ('log_path', models.CharField(max_length=500, verbose_name='日志目录路径')),
                ('env_type', models.CharField(max_length=100, verbose_name='所属环境类型')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'application',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_key', models.CharField(max_length=500, verbose_name='配置健')),
                ('conf_value', models.CharField(max_length=500, verbose_name='配置值')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'config',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_ip', models.CharField(max_length=20, verbose_name='数据库机器ip')),
                ('hostname', models.CharField(max_length=100, verbose_name='主机名')),
                ('account', models.CharField(max_length=100, verbose_name='机器账号')),
                ('password', models.CharField(max_length=100, verbose_name='机器密码')),
                ('db_name', models.CharField(max_length=100, verbose_name='数据库名称')),
                ('db_account', models.CharField(max_length=100, verbose_name='数据库账号')),
                ('db_password', models.CharField(max_length=100, verbose_name='数据库密码')),
                ('port', models.CharField(max_length=10, verbose_name='数据库端口')),
                ('env_type', models.CharField(max_length=100, verbose_name='所属环境类型')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'database',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=100, verbose_name='日志名称')),
                ('log_info', models.TextField(blank=True, null=True, verbose_name='日志内容')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('temp_type', models.CharField(default='测试', max_length=100, verbose_name='模板类型')),
                ('belong_sys', models.CharField(max_length=100, verbose_name='所属系统')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'template',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=100, verbose_name='作业名称')),
                ('work_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='作业类型')),
                ('work_status', models.CharField(max_length=100, verbose_name='作业状态')),
                ('belong_sys', models.CharField(blank=True, max_length=100, null=True, verbose_name='所属系统')),
                ('run_way', models.CharField(default='手动', max_length=10, verbose_name='执行方式')),
                ('start_time', models.IntegerField(blank=True, null=True, verbose_name='任务开始时间')),
                ('end_time', models.IntegerField(blank=True, null=True, verbose_name='任务结束时间')),
                ('total_time', models.IntegerField(blank=True, null=True, verbose_name='总耗时')),
                ('zip_name', models.TextField(blank=True, null=True, verbose_name='压缩包名')),
                ('build_time', models.IntegerField(blank=True, null=True, verbose_name='作业创建时间')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='版本号')),
                ('value_list', models.TextField(default='', verbose_name='参数列表')),
                ('temp_id', models.CharField(max_length=10, verbose_name='模板id')),
                ('webapps_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='备份文件名')),
                ('jar_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='jar包名称')),
                ('time_rule', models.CharField(blank=True, max_length=100, null=True, verbose_name='定时规则')),
                ('publish_way', models.CharField(blank=True, max_length=100, null=True, verbose_name='发布方式')),
                ('extend1', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段1')),
                ('extend2', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段2')),
                ('extend3', models.CharField(blank=True, max_length=1000, null=True, verbose_name='扩展字段3')),
            ],
            options={
                'db_table': 'work',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='work_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='environment.Work', verbose_name='作业外键'),
        ),
        migrations.AddField(
            model_name='database',
            name='temp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Template', verbose_name='模板外键'),
        ),
        migrations.AddField(
            model_name='application',
            name='temp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.Template', verbose_name='模板外键'),
        ),
    ]
